### ISSUE TITLE
Stopped

### ISSUE THREAD

**Issue by dyipon** [darkhz/rclone-tui#1]
Just installed via go install, but application is going to background instantly:
```
$ rclone-tui

[1]+  Stopped                 rclone-tui
```

How can I debug this issue?

update: its working if I'm using the pre-compiled binary

**Comment by darkhz** [comment]
Apparently go module has cached a buggy version of this repo, I'll try correcting it now

**Comment by darkhz** [comment]
I will have to release a new version to retract the buggy cached version in proxy.golang.org, upon which I will close this issue.

**Comment by dyipon** [comment]
thanks, its working!
